// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPSzWF9ZB40oVIKYNt2a-oPRxaRqC8Tao',
    appId: '1:152368802257:web:115032ab338a91d342d8f0',
    messagingSenderId: '152368802257',
    projectId: 'esms-6b9d0',
    authDomain: 'esms-6b9d0.firebaseapp.com',
    storageBucket: 'esms-6b9d0.firebasestorage.app',
    measurementId: 'G-6V420XECBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC67cja9F8nloIqWgLJrngFn8F30XTJQGs',
    appId: '1:152368802257:android:e32807877b789ed142d8f0',
    messagingSenderId: '152368802257',
    projectId: 'esms-6b9d0',
    storageBucket: 'esms-6b9d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWMuyK_F2nrUgjuY9m-NLGNdaM0KTxrJE',
    appId: '1:152368802257:ios:f7fc2995211320d042d8f0',
    messagingSenderId: '152368802257',
    projectId: 'esms-6b9d0',
    storageBucket: 'esms-6b9d0.firebasestorage.app',
    iosBundleId: 'com.example.electricalShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWMuyK_F2nrUgjuY9m-NLGNdaM0KTxrJE',
    appId: '1:152368802257:ios:f7fc2995211320d042d8f0',
    messagingSenderId: '152368802257',
    projectId: 'esms-6b9d0',
    storageBucket: 'esms-6b9d0.firebasestorage.app',
    iosBundleId: 'com.example.electricalShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPSzWF9ZB40oVIKYNt2a-oPRxaRqC8Tao',
    appId: '1:152368802257:web:5134d35dd277363442d8f0',
    messagingSenderId: '152368802257',
    projectId: 'esms-6b9d0',
    authDomain: 'esms-6b9d0.firebaseapp.com',
    storageBucket: 'esms-6b9d0.firebasestorage.app',
    measurementId: 'G-W0Z6KYYDSQ',
  );
}
